
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[APP_INFOB_SETTING](
	[FOLDERNM] [varchar](10) NOT NULL,
	[KAIINCD] [nvarchar](max) NOT NULL,
	[FLAG] [tinyint] NOT NULL,
	[MEMO] [nvarchar](200) NULL,
	[INSDAT] [datetime] NOT NULL,
	[UPDAT] [datetime] NOT NULL,
 CONSTRAINT [PK_APP_INFOB_SETTING] PRIMARY KEY CLUSTERED 
(
	[FOLDERNM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
